# Generated by Django 3.1.4 on 2021-02-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
