# Generated by Django 3.1.4 on 2021-02-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccy', models.CharField(max_length=200)),
                ('base', models.CharField(max_length=200)),
                ('buy', models.CharField(max_length=200)),
                ('sale', models.CharField(max_length=200)),
            ],
        ),
    ]
